name: Publish snake to GitHub Pages

on:
  push:
    branches:
      - main
      - develop
      - feature
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Run a one-line script
        run: echo Copying latest changes to GitHub Pages!
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: .
